// ============================================================
// Presentation_conference.typ
// Talk accompanying "Agent-Based Modelling of 'Moral Entrepreneurship'
// and the Dynamics of Moral Panics in Social Networks"
//
// Structure follows the paper: problem -> model -> results -> discussion.
// Figures live outside this folder, so compile from the repository root:
//   typst compile --root . Presentation/Presentation_conference.typ
//
// Length: 24 slides + 4 backup. Roughly 18-20 minutes at one slide per 45 s.
// ============================================================

#import "@preview/diatypst:0.9.1": *

#set text(lang: "en", region: "gb")

#show heading.where(level: 3): set heading(numbering: none)

#show: slides.with(
  title: "Agent-Based Modelling of \"Moral Entrepreneurship\" and the Dynamics of Moral Panics in Social Networks",
  subtitle: "Ignited by claims-makers, sustained by the population they divide",
  authors: ("Matvei A. Bisler", "Sergei R. Utkin"),
  date: "2026", // TODO: conference date
  footer-title: "Moral panic: an agent-based apportionment",

  ratio: 16/9,
  layout: "medium",
  title-color: blue.darken(60%),
  toc: true,
  theme: "normal",
  count: "dot-section",
)


= The problem

== A criterion the field cannot apply

Moral panic is defined partly by *disproportion*: reaction in excess of what the
situation warrants (Goode and Ben-Yehuda 1994).

Disproportion requires a comparison:

#align(center)[
  #block(inset: 8pt, radius: 4pt, fill: luma(240))[
    How alarmed would this population have been *without* the claims-making
    that alarmed it?
  ]
]

That world is not observable, so the criterion is asserted and left undemonstrated.
Hier (2024) treats it as the field's central unresolved problem.

- Reviews: panic invoked as self-evident, criteria unstated
- Consequence: no principled way to say one episode was a panic and another ordinary
  public concern

== A second gap

Entrepreneurs, folk devils and panic are studied as *three objects with three
literatures*; nobody formalises their interaction.

- Networked-panic research moved past the mass-mediated model, but entrepreneur and
  folk devil are often kept as *fixed statuses*
- Stigmatised groups routinely act as entrepreneurs of their own defence
  (Mikhaylova 2022)
- Discourse analysis, case studies and ego-network description are interpretively
  strong, but not built to show how *micro-level interaction* produces *macro-level
  escalation over time*

== What a simulation buys

Run the same population, the same network, the same initial draws, with and without
the campaign. The difference *is* disproportion, and this time it is computed.

Alarm has two manufactured sources, and each can be switched off independently:

- injected by claims-makers from outside
- generated by the population itself, through exposure to moral disagreement

#align(center)[
  #block(inset: 10pt, radius: 4pt, fill: blue.lighten(88%))[
    *A moral panic is ignited by claims-makers but sustained by the population they
    divide.*
  ]
]

*Research question.* Which claims-making strategies ignite moral panic, under which
network structures; and once ignited, what sustains it?


= The model

== Two coupled states

*Agents* on a static undirected graph. Each carries:

/ *Moral position* $b_i in [-1, 1]$: from the stigmatised pole to the dominant moral claim
/ *Alarm* $a_i in [0, 1]$: perceived social danger. *Undirected*: how alarmed, not what is feared
/ *Threshold* $theta_i$: past it, the agent amplifies (heard $gamma$ times as loudly)

*Two claims-makers outside the network.* $D$ pushes toward $+1$, $C$ toward $-1$.
Neither is an agent, neither can be alarmed. Standing outside is what makes the two
sources of alarm separable.

The *folk devil is not an actor*: it is the stigmatised pole around which alarm and
clustering emerge.

== Four rules

+ *Targeting.* Each actor reaches $rho_X N$ agents per step, by one of four
  repertoires
+ *Peer influence.* Bounded confidence: neighbours beyond tolerance $epsilon$ are
  tuned out
+ *Position.* Peers $+$ claims-maker forcing (depth $alpha_X$) $+$ noise
+ *Alarm.* $a_i (t+1) = mu a_i + delta E_i + omega Phi_i$ --- memory, contagion,
  *othering*

#v(0.4em)

#align(center)[
  #block(inset: 10pt, radius: 4pt, fill: blue.lighten(88%))[
    *The asymmetry everything rests on.* A neighbour beyond your tolerance
    contributes *nothing* to your position and *the most* to your alarm.
    A divided population manufactures its own alarm.
  ]
]

== Four repertoires, and why the fourth exists

#table(
  columns: (auto, 1fr),
  inset: 6pt,
  stroke: none,
  table.hline(),
  [`random`], [uniform subset, redrawn every step; at $rho = 1$ it is mass broadcast],
  [`hub`], [the highest-degree nodes --- influencer recruitment],
  [`base`], [the agents closest to the actor's own pole --- rallying the committed],
  [`fixed_random`], [*a control*: uniform subset drawn once, addressed every step],
  table.hline(),
)

`hub` and `base` differ from `random` in *two* ways at once: in *whom* they select,
and in selecting *the same people repeatedly*.

- `random` vs `fixed_random` #sym.arrow isolates the *exposure schedule*
- `fixed_random` vs `hub` #sym.arrow isolates *degree*

== Measuring panic: four runs on one seed

Every setting is executed four times on the identical seed (same network, same
initial positions, same thresholds):

#align(center)[
  #table(
    columns: 4,
    inset: 6pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([run], [claims-making], [othering], [notation]),
    table.hline(stroke: 0.4pt),
    [null], [off], [off], [$overline(a)^"null"$],
    [claims only], [on], [off], [$overline(a)^"cm"$],
    [othering only], [off], [on], [$overline(a)^"oth"$],
    [full], [on], [on], [$overline(a)$],
    table.hline(),
  )
]

$ overline(a) = underbrace(overline(a)^"null", "warranted") + underbrace(overline(a)^"cm" - overline(a)^"null", "claims alone") + underbrace(overline(a)^"oth" - overline(a)^"null", "othering alone") + underbrace(overline(a) - overline(a)^"cm" - overline(a)^"oth" + overline(a)^"null", "interaction") $

The *interaction* is what the design is for: alarm that exists only because both are
present. It is identically zero at $t = 1$, so it contains *no* initial dispersion.

== The panic index

$ Pi(t) = (overline(a)(t) - overline(a)^"null"(t)) / (1 - overline(a)^"null"(t)) in [0, 1] $

An *episode* = at least $W$ steps with $Pi >= Pi^*$ *and* $q >= q^*$, where $q$ is
the share of the population past threshold.

- Requiring both separates panic from widespread but proportionate concern, and from
  manipulation of a small minority
- $Pi^*, q^*, W$ are conventions #sym.arrow incidence reported over a *grid*, never at
  one cut

*Conditioning, checked at every reported point:* contagion must stay sub-critical,
or alarm self-sustains regardless of any claims-maker and the comparison loses its
meaning.

== Design

#grid(
  columns: (1.15fr, 1fr),
  gutter: 12pt,
  [
    *Operating point*
    - small world, $N = 1000$, $⟨k⟩ = 10$
    - $epsilon = 0.5$; $mu = 0.30$, $delta = 0.25$, $omega = 0.35$
    - `base`, $alpha_D = 0.7$, $rho_D = 0.25$
    - withdrawal at $t = 150$, horizon $T = 400$
    - 250 seeds #sym.arrow s.e. on incidence $<= plus.minus 0.032$
    - 72,990 counterfactual sets $=$ *291,960 runs*
  ],
  [
    *Three experiments*
    - *A* --- ignition: repertoire $times$ topology $times$ depth $times$ reach
    - *B* --- handover: withdraw $D$, sweep the alarm parameters
    - *C* --- defence: $C$ enters as $D$ leaves
  ],
)

#v(0.3em)

*Pre-registered.* Three hypotheses, and both possible outcomes of the third, fixed in
writing before the program ran. Where the runs contradicted a clause, the wording was
not revised.


= Results

== H1 --- ignition: amplification needs a stable audience

#figure(
  image("../Results/figures/fig1_h1_ignition.png", width: 76%),
)

== H1 --- what the control shows

$Pi$ at $t = 199$, small world, 250 seeds; amplification ratio $Pi slash rho_D$ in
brackets.

#align(center)[
  #table(
    columns: 5,
    inset: 5pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([$rho_D$], [`random`], [`fixed_random`], [`hub`], [`base`]),
    table.hline(stroke: 0.4pt),
    [0.02], [0.027 (1.35)], [0.031 (1.57)], [*0.078 (3.88)*], [0.029 (1.46)],
    [0.10], [0.020 (0.20)], [0.134 (1.34)], [*0.296 (2.96)*], [0.119 (1.19)],
    [0.25], [0.044 (0.18)], [0.306 (1.22)], [*0.336 (1.34)*], [0.287 (1.15)],
    [0.50], [0.087 (0.17)], [*0.435 (0.87)*], [0.352 (0.70)], [0.429 (0.86)],
    [1.00], [0.182 (0.18)], [0.182 (0.18)], [0.182 (0.18)], [0.182 (0.18)],
    table.hline(),
  )
]

- `random` never clears the diagonal at any reach, flat at $Pi slash rho approx 0.18$
- `fixed_random` traces `base` almost exactly, and carries *no degree signal at all*
- *Schedule* is worth up to $7.0 times$; *degree* a further $2.2$–$2.5 times$, and only
  below $rho_D = 0.10$

== H1 --- depth is a gate, reach is the dial

- Below $alpha_D (1 - overline(b)) approx epsilon$ the entrepreneur *converts*: reached
  agents stay audible, $overline(b) arrow 0.99$, interaction $= 0$. No reach ignites
  anything.
- Above it, $alpha_D$ stops mattering (0.70 / 0.80 / 0.90 within 0.02) and $rho_D$
  takes over: $Pi$ moves six-fold along a row.
- The gate is *bistable* between $alpha_D = 0.62$ and $0.68$: across-seed s.d.
  inflates $0.014 arrow 0.064$.

#align(center)[
  #block(inset: 10pt, radius: 4pt, fill: blue.lighten(88%))[
    *Mass broadcast unites.* At $rho_D = 1$ every repertoire is the same rule,
    exposure variance is exactly zero, the interaction collapses to 0.002 and panic
    incidence is *0.00 under every cut of the criterion*.
  ]
]

Legitimacy-as-access survives, with a precondition: access ignites only where the
claims-making is intense enough to be *disowned*.

== H2 --- handover: where the alarm comes from

#figure(
  image("../Results/figures/fig2_h2_handover.png", width: 72%),
)

== H2 --- the apportionment

#align(center)[
  #table(
    columns: 7,
    inset: 5pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([$t$], [warranted], [claims alone], [othering alone],
                 [*interaction*], [$Pi$], [$q$]),
    table.hline(stroke: 0.4pt),
    [2], [0.0165], [0.0272], [0.0198], [*0.0366*], [0.0850], [0.100],
    [20], [0.0000], [0.0414], [0.0046], [*0.2461*], [0.2921], [0.285],
    [149], [0.0000], [0.0415], [0.0046], [*0.2430*], [0.2890], [0.288],
    table.hline(stroke: 0.3pt),
    [155], [0.0000], [0.0024], [0.0046], [*0.2378*], [0.2448], [0.259],
    [399], [0.0000], [0.0000], [0.0046], [*0.1745*], [0.1791], [0.188],
    table.hline(),
  )
]

- *14% / 2% / 84%* --- signal, pre-existing division, interaction
- Endogenous over exogenous: *5.94 to one*, reached by step 20
- 97% of the othering exposure is over distance the campaign *created*
- After withdrawal: *62% of $Pi$ still standing 250 steps later*

*The registered ordering fails.* The interaction overtakes at $t = 2$ (the earliest
step permitted) in 250/250 seeds and at every depth. An apportionment, not a
chronology.

== H2 --- what survives is othering, and only othering

#grid(
  columns: (1fr, 1fr),
  gutter: 12pt,
  [
    *Three instruments, one answer*
    - $omega$ sweep at fixed $mu + delta$: $Pi(399)$ rises monotonically
      $0.000 arrow 0.286$
    - Simplex scan: maximum sits *exactly* on the $omega$ vertex
    - Sobol: the split has $S_T = 0.99$, total intensity $0.03$
  ],
  [
    *Two audits that had to be run*
    - 4 of 45 simplex points are supercritical, all with
      $mu + delta <= 0.60$; without excluding them the scan reads as a
      *refutation*
    - Noise: over $zeta in [0, 0.05]$ the ordering *reverses*, $0.39$ against $0.75$
  ],
)

#align(center)[
  #block(inset: 8pt, radius: 4pt, fill: luma(240))[
    *Scope condition, and it travels with the result:* persistence is governed by
    othering provided $zeta lt.approx 0.02$. How noisy real moral positions are is
    not a question this model can settle.
  ]
]

== H3 --- defence: neither pre-registered branch

#figure(
  image("../Results/figures/fig3_h3_defense.png", width: 72%),
)

== H3 --- a sequence, not a sign

#align(center)[
  #table(
    columns: 6,
    inset: 5pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([configuration], [$(alpha_C, rho_C)$], [peak $Pi$], [excess],
                 [steps above], [$Pi(399)$]),
    table.hline(stroke: 0.4pt),
    [none (baseline)], [(---, 0)], [0.289], [---], [---], [0.179],
    [broad and shallow], [(0.15, 0.60)], [0.329], [+0.077], [9], [0.106],
    [narrow and deep], [(0.90, 0.10)], [*0.467*], [*+0.239*], [24], [*0.020*],
    [matched], [(0.70, 0.25)], [0.380], [+0.135], [11], [0.045],
    table.hline(),
  )
]

- Every configuration *raises* $Pi$ for 9–24 steps, then lowers it permanently
- The largest overshoot belongs to the *lowest-reach* configuration #sym.arrow that
  rules out the cost channel. What produces it is the second: pulling a tenth of the
  population to $-1$ maximises distance to a bulk sitting at $overline(b) = +0.29$
- The reduction is *conversion, not reassurance*: $overline(b) arrow -0.99$,
  $overline(Phi) arrow 0.005$
- A permanent floor $approx 0.18 rho_C$: linear in reach, flat in depth --- *the price
  of speaking*

== Robustness

- *Population size:* $Pi(149) = 0.292 / 0.292 / 0.293$ at $N = 500 / 1000 / 2000$
- *Update scheme:* synchronous vs asynchronous differ by 0.010, inside seed dispersion
- *Two empirical graphs* $+$ matched generators: during the campaign $Pi$ lies in
  $0.227$–$0.270$ across an eightfold range of mean degree
- *But what survives is structural.* At $⟨k⟩ = 5.5$, retained $Pi(399)$
  tracks clustering: $0.135 / 0.100 / 0.072 / bold(0.006)$
- *Boundary artifact cleared:* interior bimodality matches the raw coefficient to
  three decimals
- *Validity horizon* at $t = 191$–$289$ in 3 of 5 audited seeds #sym.arrow late-run
  quantities reported as seed distributions, never as trajectories


= What it means

== Three predictions for empirical work

/ *Ignition is repetition, not reach*: The mass broadcaster is structurally the worst available entrepreneur. Fragmentation of audiences is *itself a mechanism*, and the measurable quantity is the *concentration* of exposure.

/ *Local density decides permanence*: Two societies with identical claims-making, tolerance and alarm parameters differ in whether the panic outlives the campaign, according to how *clustered* their ties are. No synthetic generator produced this.

/ *Answering back intensifies first*: And most when most committed. No tone, no provocation, no backlash psychology in the model. Just arithmetic on moral distance: the defence's own converts become the population's most distant neighbours.

== What the apportionment settles

The elite-driven / interactionist dispute becomes a number: *14 : 2 : 84*.

- The entrepreneur is *necessary* (at $rho_D = 0$ nothing happens) and nearly
  irrelevant to the *magnitude*
- Its achievement is to divide the population far enough that alarm becomes
  self-sustaining, after which it can leave

#align(center)[
  #block(inset: 10pt, radius: 4pt, fill: blue.lighten(88%))[
    Withdrawing the claims-making that started a panic does not remove what is
    keeping it going. The only thing that returns $Pi$ to zero is $omega = 0$:
    a population that does not find disagreement frightening.
  ]
]

That is a different object of intervention from "stop the campaign".

== What bounds it

*The hard ceiling.* $Pi$ is excess over the *model's own* counterfactual, not over
real danger. The disproportionality criterion is made *computable*, not *decidable*.

#grid(
  columns: (1fr, 1fr),
  gutter: 12pt,
  [
    *Exclusions*
    - networks do not rewire; no repulsion
    - no algorithm, no recommender
    - no actor can reassure
    - no institutional legacy
    - claims-makers do not learn
  ],
  [
    *Scope conditions*
    - $sigma = 0$ (no restoring force)
    - $zeta lt.approx 0.02$ (position noise)
    - consensual start
    - sub-criticality re-checked at every point
  ],
)

Six parameters, but roughly *three live dimensions*: the depth–tolerance gate, reach,
and othering.

== Takeaway

The three transferable results are *negative in form*:

+ Claims-making that reaches *everyone* cannot produce a panic --- manufactured
  division requires *unequal* exposure
+ Claims-making too shallow to be *disowned* cannot produce one either --- it
  persuades instead of dividing
+ Answering back cannot lower alarm without first raising it --- the only channel
  open is the elimination of disagreement

#align(center)[
  #block(inset: 10pt, radius: 4pt, fill: blue.lighten(88%))[
    If moral panics are becoming easier to start, the reason is not that reach has
    increased.
  ]
]

#v(0.5em)

#align(center)[*Thank you.* Questions welcome.]


= Backup

== Exposure concentration

$"Var"_i (sum_t g^D_i)$ at $rho_D = 0.10$ over 200 steps:

#align(center)[
  #table(
    columns: 5,
    inset: 6pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([topology], [`random`], [`fixed_random`], [`hub`], [`base`]),
    table.hline(stroke: 0.4pt),
    [Watts--Strogatz], [18], [3600], [2272], [3567],
    [Holme--Kim], [18], [3600], [3519], [3569],
    [Erdős--Rényi], [18], [3600], [3224], [3443],
    table.hline(),
  )
]

3600 is the attainable maximum. `hub` is *less* concentrated than the control on
every topology and still beats it at low reach. That is what identifies degree as a
second, independent channel, not a re-description of the schedule.

== The tipping point is in the instrument

`base`, small world, $W = 10$, 250 seeds:

#align(center)[
  #table(
    columns: 4,
    inset: 5pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([$rho_D$], [incidence at $Pi^* = 0.2, q^* = 0.2$],
                 [$Pi$], [across-seed s.d.]),
    table.hline(stroke: 0.4pt),
    [0.15], [0.08], [0.177], [0.015],
    [0.20], [0.96], [0.234], [0.015],
    [1.00], [0.00], [0.182], [0.004],
    table.hline(),
  )
]

A step function applied to a smooth quantity with small variance *is* a step
function. Empirical episode counts may inherit their sharpness from the coding rule.

== Verification

The code is docked against five models with known behaviour:

+ plain neighbour averaging (DeGroot) --- consensus on any connected non-bipartite graph
+ Friedkin--Johnsen --- the analytic equilibrium
+ Hegselmann--Krause --- the known $epsilon$-dependence of the cluster count
+ mean-field fixed point of the alarm recursion
+ empty graph --- full and null runs coincide, $Pi equiv 0$

*14 / 14 checks pass.* The Saltelli/Jansen estimator is written directly and docked
against the Ishigami function to within 0.0025.

Randomness: one recorded seed, three named substreams (setup, targeting, noise).
Sharing a stream between targeting and noise would desynchronise the four arms and
destroy the counterfactual.

== The anchor, and why $sigma = 0$

#align(center)[
  #table(
    columns: 4,
    inset: 6pt,
    align: center,
    stroke: none,
    table.hline(),
    table.header([$sigma$], [predicted $-1 slash ln(1 - sigma)$], [measured persistence],
                 [$Pi$ 250 steps after withdrawal]),
    table.hline(stroke: 0.4pt),
    [0.00], [$infinity$], [censored], [0.179],
    [0.05], [19.5], [13], [0.005],
    [0.10], [9.5], [9], [0.007],
    [0.20], [4.5], [4], [---],
    table.hline(),
  )
]

The anchor is a restoring force toward each agent's *pre-campaign* position, which
under a consensual start sits near zero. Any positive $sigma$ dissolves the
manufactured division on its own timescale, whatever $omega$ is: the reverse of
H2. Fixing it positive and leaving it outside the analysis would have handed the
whole result to a constant nobody was looking at.
